name: driver_test_apps
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  http: ^1.1.2
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  step_progress_indicator: ^1.0.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/menu/
    - assets/images/quiz/
    - assets/images/sosmed/
    - assets/images/navigation/
    - assets/images/icons/
    - assets/images/signs/
    - assets/lottie/
    - assets/lottie/onboarding/

flutter_gen:
  output: lib/core/assets/
